# Generated by Django 5.1 on 2024-08-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_wishitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
