# Generated by Django 5.1 on 2024-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_best_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='available_colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='available_sizes',
            field=models.JSONField(default=list),
        ),
    ]
